In [14]:
import numpy as np
import pandas as pd
import json
import gzip
import seaborn as sns
import os
%matplotlib inline

data_dir = 'C:\Codes\Data-engineering\data'
profiles_path = os.path.join(data_dir, 'linkedin.json')
print(os.listdir(data_dir))

['linkedin.edges', 'linkedin.json', 'linkedin.nodes']

In [19]:
num_records = 0
for line in open(profiles_path,'rb'):
    num_records += 1
print('Number of profiles', num_records)

Number of profiles 2985334

In [25]:
fields = set()
localities = []
industries = []
skills = []
specialities = []
interests = []
occupations = []
companies = []
schools = []
majors = []

for line in open(profiles_path,'rb'):
    line = json.loads(line)
    
    fields.update(line.keys())
    
    localities.append(line['locality'] if 'locality' in line else '')
    industries.append(line['industry'] if 'industry' in line else '')
    skills.extend(line['skills'] if 'skills' in line else [])
    specialities.extend([s.strip() for s in line['specilities'].split(',')] if 'specilities' in line else [])
    interests.extend([s.strip() for s in line['interests'].split(',')] if 'interests' in line else [])
    occupations.extend([exp['title'] for exp in line['experience'] if 'title' in exp] if 'experience' in line else [])
    companies.extend([exp['org'] for exp in line['experience'] if 'org' in exp] if 'experience' in line else [])
    schools.extend([edu['name'] for edu in line['education'] if 'name' in edu] if 'education' in line else [])
    majors.extend([edu['major'] for edu in line['education'] if 'major' in edu] if 'education' in line else [])
    
print('JSON fields', len(fields), fields)

JSON fields 18 {'group', 'overview_html', 'events', 'industry', 'interests', 'also_view', 'url', 'interval', 'specilities', '_id', 'experience', 'homepage', 'honors', 'locality', 'name', 'skills', 'education', 'summary'}

In [28]:
type(skills)

list

In [48]:
skills = pd.Series(list(skills)).value_counts()
localities = pd.Series(list(localities)).value_counts()
industries = pd.Series(list(industries)).value_counts()
specialities = pd.Series(list(specialities)).value_counts()
interests = pd.Series(list(interests)).value_counts()
occupations = pd.Series(list(occupations)).value_counts()
companies = pd.Series(list(companies)).value_counts()
schools = pd.Series(list(schools)).value_counts()
majors = pd.Series(list(majors)).value_counts()

print(len(skills))
print(len(localities))
print(len(industries))
print(len(specialities))
print(len(interests))
print(len(occupations))
print(len(companies))
print(len(schools))
print(len(majors))

653628
24598
2646
861527
557665
3500534
3787170
864915
733611

In [33]:
num_profiles_loaded = 1000
profiles = []

for line in open(profiles_path,'rb'):
    if len(profiles) < num_profiles_loaded:
        line = json.loads(line)
        profiles.append(line)
    else:
        break
        
#print('Examples primary keys', [p['_id'] type(p) for p in profiles[:10]])

In [49]:
skills_count = skills[skills >= 10]

skills_count = pd.DataFrame(skills_count, columns=['Count'])
skills_count['Skill'] = skills_count.index
skills_count['Rank'] = range(1,len(skills_count)+1)
skills_count['Cumulative Probability'] = np.cumsum(skills_count.Count)/np.sum(skills_count.Count)

print('Number of skills', len(skills_count))
skills_count

Number of skills 33489

,Count,Skill,Rank,Cumulative Probability
Microsoft Office,149914,Microsoft Office,1,0.009359
Strategic Planning,123673,Strategic Planning,2,0.017080
Project Management,115735,Project Management,3,0.024305
Business Strategy,104696,Business Strategy,4,0.030841
Marketing Strategy,96228,Marketing Strategy,5,0.036848
Negotiation,92935,Negotiation,6,0.042650
New Business Development,91805,New Business Development,7,0.048381
Change Management,91090,Change Management,8,0.054067
Sales Management,83066,Sales Management,9,0.059253
Social Media,81731,Social Media,10,0.064355
Customer Service,79410,Customer Service,11,0.069313
Microsoft Excel,77734,Microsoft Excel,12,0.074166
Team Leadership,76692,Team Leadership,13,0.078953
PowerPoint,68052,PowerPoint,14,0.083202
Account Management,62874,Account Management,15,0.087127
English,59601,English,16,0.090848
Research,59427,Research,17,0.094557
Business Analysis,59144,Business Analysis,18,0.098250
Marketing Communications,58700,Marketing Communications,19,0.101914
Product Development,58154,Product Development,20,0.105545
Team Building,57485,Team Building,21,0.109133
Java,54398,Java,22,0.112529
Business Development,54147,Business Development,23,0.115910
Coaching,52619,Coaching,24,0.119195
Microsoft Word,50166,Microsoft Word,25,0.122326
SQL,49789,SQL,26,0.125435
Public Relations,49280,Public Relations,27,0.128511
Team Management,48344,Team Management,28,0.131529
Photoshop,48082,Photoshop,29,0.134531
Recruiting,47805,Recruiting,30,0.137515
...,...,...,...,...
customer care,10,customer care,33460,0.999982
Profissionalismo,10,Profissionalismo,33461,0.999983
Budgeting and Planning,10,Budgeting and Planning,33462,0.999983
SQL Server DBA,10,SQL Server DBA,33463,0.999984
Locución,10,Locución,33464,0.999984
Spirit,10,Spirit,33465,0.999985
Consciência da qualidade,10,Consciência da qualidade,33466,0.999986
Techno-economic Analysis,10,Techno-economic Analysis,33467,0.999986
MD&A,10,MD&A,33468,0.999987
ADRs,10,ADRs,33469,0.999988
Fluent Mandarin,10,Fluent Mandarin,33470,0.999988
WFO,10,WFO,33471,0.999989
REVIT,10,REVIT,33472,0.999989
trabajo bajo presión,10,trabajo bajo presión,33473,0.999990
JBOSS,10,JBOSS,33474,0.999991
Siperian,10,Siperian,33475,0.999991
Clintrial,10,Clintrial,33476,0.999992
Change Catalyst,10,Change Catalyst,33477,0.999993
Optimism,10,Optimism,33478,0.999993
COMERCIAL,10,COMERCIAL,33479,0.999994
Certified Hazardous Materials Manager,10,Certified Hazardous Materials Manager,33480,0.999994
Suicide Intervention,10,Suicide Intervention,33481,0.999995
SPME,10,SPME,33482,0.999996
L-1,10,L-1,33483,0.999996
Media &amp; Entertainment,10,Media &amp; Entertainment,33484,0.999997
Risk Assessment and Management,10,Risk Assessment and Management,33485,0.999998
Strong written and verbal communication skills,10,Strong written and verbal communication skills,33486,0.999998
P&L Reporting,10,P&L Reporting,33487,0.999999
Fluke,10,Fluke,33488,0.999999
Entertainer,10,Entertainer,33489,1.000000

In [18]:
locations_count = localities[localities >= 10]

locations_count = pd.DataFrame(locations_count, columns=['Count'])
locations_count['Location'] = locations_count.index
locations_count['Rank'] = range(1,len(locations_count)+1)
locations_count['Cumulative Probability'] = np.cumsum(locations_count.Count)/np.sum(locations_count.Count)

print('Number of locations', len(locations_count))
locations_count

Number of locations 5968

,Count,Location,Rank,Cumulative Probability
Greater New York City Area,81502,Greater New York City Area,1,0.027736
"London, United Kingdom",76516,"London, United Kingdom",2,0.053775
San Francisco Bay Area,53998,San Francisco Bay Area,3,0.072152
United Kingdom,45388,United Kingdom,4,0.087598
"Toronto, Canada Area",38505,"Toronto, Canada Area",5,0.100701
"Sydney Area, Australia",36360,"Sydney Area, Australia",6,0.113075
Argentina,34775,Argentina,7,0.124910
Greater Boston Area,34231,Greater Boston Area,8,0.136559
Greater Chicago Area,33351,Greater Chicago Area,9,0.147908
Singapore,28971,Singapore,10,0.157768
United Arab Emirates,28924,United Arab Emirates,11,0.167611
Greater Los Angeles Area,28791,Greater Los Angeles Area,12,0.177409
"Région de Paris , France",28271,"Région de Paris , France",13,0.187030
"Mumbai Area, India",27194,"Mumbai Area, India",14,0.196284
"Amsterdam Area, Netherlands",26108,"Amsterdam Area, Netherlands",15,0.205169
Chile,26064,Chile,16,0.214039
"Melbourne Area, Australia",25772,"Melbourne Area, Australia",17,0.222809
Washington D.C. Metro Area,25355,Washington D.C. Metro Area,18,0.231438
"São Paulo e Região, Brasil",24672,"São Paulo e Região, Brasil",19,0.239834
"Paris Area, France",22891,"Paris Area, France",20,0.247624
"New Delhi Area, India",22396,"New Delhi Area, India",21,0.255246
Ireland,22026,Ireland,22,0.262742
"São Paulo Area, Brazil",21870,"São Paulo Area, Brazil",23,0.270184
"Bengaluru Area, India",21398,"Bengaluru Area, India",24,0.277466
"Madrid y alrededores, España",20798,"Madrid y alrededores, España",25,0.284544
"Copenhagen Area, Denmark",20650,"Copenhagen Area, Denmark",26,0.291572
China,20577,China,27,0.298574
Dallas/Fort Worth Area,19138,Dallas/Fort Worth Area,28,0.305087
Greater Atlanta Area,18452,Greater Atlanta Area,29,0.311367
"Houston, Texas Area",17505,"Houston, Texas Area",30,0.317324
...,...,...,...,...
Vénézuela,10,Vénézuela,5939,0.999901
"Macungie, Pennsylvania",10,"Macungie, Pennsylvania",5940,0.999905
"Lake Elsinore, California",10,"Lake Elsinore, California",5941,0.999908
"Lindfield, West Sussex, United Kingdom",10,"Lindfield, West Sussex, United Kingdom",5942,0.999912
"Lenham, Kent, United Kingdom",10,"Lenham, Kent, United Kingdom",5943,0.999915
"Barton-upon-Humber, North Lincolnshire, United Kingdom",10,"Barton-upon-Humber, North Lincolnshire, United...",5944,0.999918
"Quakertown, Pennsylvania",10,"Quakertown, Pennsylvania",5945,0.999922
"Waterville, Maine",10,"Waterville, Maine",5946,0.999925
"Stockport, Greater Manchester, United Kingdom",10,"Stockport, Greater Manchester, United Kingdom",5947,0.999929
"Tooele, Utah",10,"Tooele, Utah",5948,0.999932
"Tonawanda, New York",10,"Tonawanda, New York",5949,0.999935
"Merrillville, Indiana",10,"Merrillville, Indiana",5950,0.999939
"Huntington, West Virginia",10,"Huntington, West Virginia",5951,0.999942
"Owen Sound, Ontario, Canada",10,"Owen Sound, Ontario, Canada",5952,0.999946
"Dekalb, Illinois",10,"Dekalb, Illinois",5953,0.999949
"Berlin, Maryland",10,"Berlin, Maryland",5954,0.999952
"Summertown, Oxfordshire, United Kingdom",10,"Summertown, Oxfordshire, United Kingdom",5955,0.999956
"Middletown, New York",10,"Middletown, New York",5956,0.999959
"Erie, Colorado",10,"Erie, Colorado",5957,0.999963
"Ashland, Ohio",10,"Ashland, Ohio",5958,0.999966
"Nova Friburgo Area, Brazil",10,"Nova Friburgo Area, Brazil",5959,0.999969
"Oxford, Royaume-Uni",10,"Oxford, Royaume-Uni",5960,0.999973
"Belo Horizonte y alrededores, Brasil",10,"Belo Horizonte y alrededores, Brasil",5961,0.999976
"Willowbrook, Illinois",10,"Willowbrook, Illinois",5962,0.999980
"Hurst, Greater Manchester, United Kingdom",10,"Hurst, Greater Manchester, United Kingdom",5963,0.999983
"Carmarthen, Carmarthenshire, United Kingdom",10,"Carmarthen, Carmarthenshire, United Kingdom",5964,0.999986
"Galashiels, Scottish Borders, United Kingdom",10,"Galashiels, Scottish Borders, United Kingdom",5965,0.999990
"Valença e Região, Brasil",10,"Valença e Região, Brasil",5966,0.999993
"Finspang, Sweden",10,"Finspang, Sweden",5967,0.999997
"Aksaray, Türkiye",10,"Aksaray, Türkiye",5968,1.000000

In [19]:
industries_count = industries[industries >= 10]

industries_count = pd.DataFrame(industries_count, columns=['Count'])
industries_count['Industry'] = industries_count.index
industries_count['Rank'] = range(1,len(industries_count)+1)
industries_count['Cumulative Probability'] = np.cumsum(industries_count.Count)/np.sum(industries_count.Count)

print('Number of industries', len(industries_count))
industries_count

Number of industries 2317

,Count,Industry,Rank,Cumulative Probability
Information Technology and Services,167289,Information Technology and Services,1,0.056065
Computer Software,90346,Computer Software,2,0.086343
Financial Services,89304,Financial Services,3,0.116272
,81615,,4,0.143624
Marketing and Advertising,74079,Marketing and Advertising,5,0.168451
Oil & Energy,64818,Oil & Energy,6,0.190173
Telecommunications,54424,Telecommunications,7,0.208413
Banking,47001,Banking,8,0.224165
Human Resources,44230,Human Resources,9,0.238988
Pharmaceuticals,43666,Pharmaceuticals,10,0.253622
Construction,43108,Construction,11,0.268069
Accounting,38963,Accounting,12,0.281127
Retail,37847,Retail,13,0.293811
Internet,37797,Internet,14,0.306478
Management Consulting,36071,Management Consulting,15,0.318566
Hospital & Health Care,34188,Hospital & Health Care,16,0.330024
Insurance,30806,Insurance,17,0.340348
Staffing and Recruiting,29013,Staffing and Recruiting,18,0.350072
Real Estate,28483,Real Estate,19,0.359617
Higher Education,28200,Higher Education,20,0.369068
Automotive,26981,Automotive,21,0.378110
Law Practice,26390,Law Practice,22,0.386955
Research,24784,Research,23,0.395261
Design,24470,Design,24,0.403461
Consumer Goods,24437,Consumer Goods,25,0.411651
Education Management,23616,Education Management,26,0.419566
Hospitality,23468,Hospitality,27,0.427431
Electrical/Electronic Manufacturing,23035,Electrical/Electronic Manufacturing,28,0.435151
Mining & Metals,19591,Mining & Metals,29,0.441716
Mechanical or Industrial Engineering,19359,Mechanical or Industrial Engineering,30,0.448204
...,...,...,...,...
Penegakan Hukum,11,Penegakan Hukum,2288,0.999903
Politi,10,Politi,2289,0.999906
섬유,10,섬유,2290,0.999910
Relacje rządowe,10,Relacje rządowe,2291,0.999913
Permainan Komputer,10,Permainan Komputer,2292,0.999916
Kamu Güvenliği,10,Kamu Güvenliği,2293,0.999920
요식업,10,요식업,2294,0.999923
"Glas-, keramik- och betongbranschen",10,"Glas-, keramik- och betongbranschen",2295,0.999926
이벤트 서비스,10,이벤트 서비스,2296,0.999930
Magistratură,10,Magistratură,2297,0.999933
E-ラーニング,10,E-ラーニング,2298,0.999936
번역 및 현지화,10,번역 및 현지화,2299,0.999940
Seni Rupa,10,Seni Rupa,2300,0.999943
Settore pesca,10,Settore pesca,2301,0.999946
Lembaga Keagamaan,10,Lembaga Keagamaan,2302,0.999950
Bireysel ve Aile Hizmetleri,10,Bireysel ve Aile Hizmetleri,2303,0.999953
Polizeidienst,10,Polizeidienst,2304,0.999956
Rozwiązania bezprzewodowe,10,Rozwiązania bezprzewodowe,2305,0.999960
Produk Kertas & Perhutanan,10,Produk Kertas & Perhutanan,2306,0.999963
アニメーション,10,アニメーション,2307,0.999966
방송 미디어,10,방송 미디어,2308,0.999970
Wadah Pemikir,10,Wadah Pemikir,2309,0.999973
Полимерная промышленность,10,Полимерная промышленность,2310,0.999977
Balírenský a kontejnerový průmysl,10,Balírenský a kontejnerový průmysl,2311,0.999980
환경 서비스,10,환경 서비스,2312,0.999983
Velgørenhed,10,Velgørenhed,2313,0.999987
Organizacje publiczne i społeczne,10,Organizacje publiczne i społeczne,2314,0.999990
Luxusní zboží a klenotnictví,10,Luxusní zboží a klenotnictví,2315,0.999993
정부 행정,10,정부 행정,2316,0.999997
Pertahanan & Angkasa,10,Pertahanan & Angkasa,2317,1.000000

In [20]:
specialities_count = specialities[specialities >= 10]

specialities_count = pd.DataFrame(specialities_count, columns=['Count'])
specialities_count['Specialities'] = specialities_count.index
specialities_count['Rank'] = range(1,len(specialities_count)+1)
specialities_count['Cumulative Probability'] = np.cumsum(specialities_count.Count)/np.sum(specialities_count.Count)

print('Number of specialities', len(specialities_count))
specialities_count

Number of specialities 15956

,Count,Specialities,Rank,Cumulative Probability
,16231,,1,0.014466
Project Management,11233,Project Management,2,0.024477
Marketing,7160,Marketing,3,0.030858
project management,7136,project management,4,0.037218
marketing,6869,marketing,5,0.043340
Business Development,5868,Business Development,6,0.048570
Sales,5250,Sales,7,0.053249
Java,5022,Java,8,0.057725
sales,4978,sales,9,0.062161
HTML,4603,HTML,10,0.066264
CSS,4185,CSS,11,0.069994
microsoft office,3889,microsoft office,12,0.073460
microsoft excel,3844,microsoft excel,13,0.076886
PHP,3734,PHP,14,0.080214
C#,3601,C#,15,0.083423
customer relations,3583,customer relations,16,0.086616
business development,3490,business development,17,0.089727
microsoft word,3489,microsoft word,18,0.092836
XML,3429,XML,19,0.095892
management,3177,management,20,0.098724
SQL,3151,SQL,21,0.101532
microsoft powerpoint,3078,microsoft powerpoint,22,0.104275
C++,2975,C++,23,0.106927
JavaScript,2946,JavaScript,24,0.109552
budgeting,2842,budgeting,25,0.112085
Social Media,2610,Social Media,26,0.114411
social media,2610,social media,27,0.116738
Change Management,2585,Change Management,28,0.119041
leadership,2576,leadership,29,0.121337
Strategic Planning,2574,Strategic Planning,30,0.123631
...,...,...,...,...
User interface,10,User interface,15927,0.999742
GXT,10,GXT,15928,0.999750
Schrijven,10,Schrijven,15929,0.999759
Desarrollo de productos,10,Desarrollo de productos,15930,0.999768
turn-around,10,turn-around,15931,0.999777
Desenvolvimento Organizacional,10,Desenvolvimento Organizacional,15932,0.999786
CS3,10,CS3,15933,0.999795
web design & development,10,web design & development,15934,0.999804
Cash Flow Forecasting,10,Cash Flow Forecasting,15935,0.999813
knowledge representation,10,knowledge representation,15936,0.999822
Jmeter,10,Jmeter,15937,0.999831
Continous Improvement,10,Continous Improvement,15938,0.999840
As above,10,As above,15939,0.999848
VoD,10,VoD,15940,0.999857
presentaciones,10,presentaciones,15941,0.999866
Hidráulica,10,Hidráulica,15942,0.999875
Gameplay Programming,10,Gameplay Programming,15943,0.999884
Domino,10,Domino,15944,0.999893
Solar Power,10,Solar Power,15945,0.999902
DELL,10,DELL,15946,0.999911
PSA,10,PSA,15947,0.999920
Recruitment Technology,10,Recruitment Technology,15948,0.999929
Commerce Server,10,Commerce Server,15949,0.999938
Water Quality,10,Water Quality,15950,0.999947
Solution Architecting,10,Solution Architecting,15951,0.999955
Supplier,10,Supplier,15952,0.999964
process definition,10,process definition,15953,0.999973
Biophysics,10,Biophysics,15954,0.999982
Field Operations,10,Field Operations,15955,0.999991
2003),10,2003),15956,1.000000

In [21]:
interests_count = interests[interests >= 10]

interests_count = pd.DataFrame(interests_count, columns=['Count'])
interests_count['Interests'] = interests_count.index
interests_count['Rank'] = range(1,len(interests_count)+1)
interests_count['Cumulative Probability'] = np.cumsum(interests_count.Count)/np.sum(interests_count.Count)

print('Number of interests', len(interests_count))
interests_count

Number of interests 11380

,Count,Interests,Rank,Cumulative Probability
reading,14645,reading,1,0.013338
Music,14372,Music,2,0.026428
Reading,14203,Reading,3,0.039364
,13955,,4,0.052073
music,11925,music,5,0.062934
Photography,11737,Photography,6,0.073624
Golf,11592,Golf,7,0.084182
photography,9481,photography,8,0.092817
Travel,9460,Travel,9,0.101433
travel,8941,travel,10,0.109576
new technology,7286,new technology,11,0.116212
skiing,7255,skiing,12,0.122819
Travelling,7209,Travelling,13,0.129385
cooking,7128,cooking,14,0.135877
traveling,6769,traveling,15,0.142042
Traveling,6636,Traveling,16,0.148086
travelling,6435,travelling,17,0.153947
Running,6235,Running,18,0.159625
running,6193,running,19,0.165266
Football,6156,Football,20,0.170872
Tennis,6071,Tennis,21,0.176402
Skiing,5838,Skiing,22,0.181719
golf,5836,golf,23,0.187034
hiking,5596,hiking,24,0.192131
swimming,5418,swimming,25,0.197065
Sports,5352,Sports,26,0.201940
tennis,5200,tennis,27,0.206676
Cooking,5193,Cooking,28,0.211405
Technology,4960,Technology,29,0.215923
Swimming,4747,Swimming,30,0.220246
...,...,...,...,...
SolidWorks,10,SolidWorks,11351,0.999736
body boarding,10,body boarding,11352,0.999745
deporte en general,10,deporte en general,11353,0.999754
Synthetic Biology,10,Synthetic Biology,11354,0.999763
Aquaculture,10,Aquaculture,11355,0.999772
and technology.,10,and technology.,11356,0.999781
Beatles,10,Beatles,11357,0.999791
wakeboarden,10,wakeboarden,11358,0.999800
Sociedad,10,Sociedad,11359,0.999809
video game design,10,video game design,11360,0.999818
golf and reading,10,golf and reading,11361,0.999827
Technology Integration,10,Technology Integration,11362,0.999836
Bungee jumping,10,Bungee jumping,11363,0.999845
Photografy,10,Photografy,11364,0.999854
trabajo,10,trabajo,11365,0.999863
Legal services,10,Legal services,11366,0.999872
pop-culture,10,pop-culture,11367,0.999882
Non-profit,10,Non-profit,11368,0.999891
Partnership,10,Partnership,11369,0.999900
Personalization,10,Personalization,11370,0.999909
Interactivity,10,Interactivity,11371,0.999918
dentistry,10,dentistry,11372,0.999927
Formula One Racing,10,Formula One Racing,11373,0.999936
Customer Care,10,Customer Care,11374,0.999945
reading news,10,reading news,11375,0.999954
horsebackriding,10,horsebackriding,11376,0.999964
Corrosion,10,Corrosion,11377,0.999973
Maghreb,10,Maghreb,11378,0.999982
Game Fishing,10,Game Fishing,11379,0.999991
children's literature,10,children's literature,11380,1.000000

In [22]:
occupations_count = occupations[occupations >= 10]

occupations_count = pd.DataFrame(occupations_count, columns=['Count'])
occupations_count['Occupations'] = occupations_count.index
occupations_count['Rank'] = range(1,len(occupations_count)+1)
occupations_count['Cumulative Probability'] = np.cumsum(occupations_count.Count)/np.sum(occupations_count.Count)

print('Number of occupations', len(occupations_count))
occupations_count

Number of occupations 56823

,Count,Occupations,Rank,Cumulative Probability
Owner,75722,Owner,1,0.014272
Project Manager,68503,Project Manager,2,0.027182
Consultant,64052,Consultant,3,0.039255
Director,59652,Director,4,0.050497
Intern,55371,Intern,5,0.060933
Account Manager,40761,Account Manager,6,0.068616
Software Engineer,39704,Software Engineer,7,0.076099
Manager,36578,Manager,8,0.082993
Managing Director,35297,Managing Director,9,0.089645
General Manager,31269,General Manager,10,0.095538
President,29705,President,11,0.101137
Sales Manager,28322,Sales Manager,12,0.106475
CEO,27166,CEO,13,0.111595
Associate,26604,Associate,14,0.116609
Account Executive,24944,Account Executive,15,0.121310
Partner,23769,Partner,16,0.125790
Senior Consultant,22833,Senior Consultant,17,0.130094
Vice President,21734,Vice President,18,0.134190
Business Development Manager,21351,Business Development Manager,19,0.138214
Marketing Manager,20621,Marketing Manager,20,0.142100
Product Manager,19227,Product Manager,21,0.145724
Research Assistant,18936,Research Assistant,22,0.149293
Software Developer,17347,Software Developer,23,0.152563
Business Analyst,17328,Business Analyst,24,0.155828
Analyst,15353,Analyst,25,0.158722
Operations Manager,14982,Operations Manager,26,0.161546
Trainee,14979,Trainee,27,0.164369
Project Engineer,14877,Project Engineer,28,0.167173
Senior Software Engineer,13572,Senior Software Engineer,29,0.169731
Engineer,13471,Engineer,30,0.172270
...,...,...,...,...
Co-Store Manager,10,Co-Store Manager,56794,0.999945
Trade Sector Manager,10,Trade Sector Manager,56795,0.999947
Business Development & Strategy Manager,10,Business Development & Strategy Manager,56796,0.999949
calidad,10,calidad,56797,0.999951
Senior Strength & Conditioning Coach,10,Senior Strength & Conditioning Coach,56798,0.999953
Onsite Lead,10,Onsite Lead,56799,0.999955
Systemspecialist,10,Systemspecialist,56800,0.999957
Teacher Librarian,10,Teacher Librarian,56801,0.999959
Contract CFO,10,Contract CFO,56802,0.999960
Freelance Photography,10,Freelance Photography,56803,0.999962
"Senior Consultant, Advisory Services",10,"Senior Consultant, Advisory Services",56804,0.999964
Vice President/Creative Director,10,Vice President/Creative Director,56805,0.999966
Senior Systems Tester,10,Senior Systems Tester,56806,0.999968
Executiva de Negocios,10,Executiva de Negocios,56807,0.999970
French Translator,10,French Translator,56808,0.999972
Gestor Financiero,10,Gestor Financiero,56809,0.999974
Analista de Suporte Técnico Pleno,10,Analista de Suporte Técnico Pleno,56810,0.999975
Generalista de RH,10,Generalista de RH,56811,0.999977
FIELD SALES MANAGER,10,FIELD SALES MANAGER,56812,0.999979
Costs Lawyer,10,Costs Lawyer,56813,0.999981
Postdoc research fellow,10,Postdoc research fellow,56814,0.999983
application specialist,10,application specialist,56815,0.999985
SENIOR OFFICER,10,SENIOR OFFICER,56816,0.999987
Freelance 3D generalist,10,Freelance 3D generalist,56817,0.999989
SW team leader,10,SW team leader,56818,0.999991
Junior Mentor,10,Junior Mentor,56819,0.999992
Executive-Regulatory Affairs,10,Executive-Regulatory Affairs,56820,0.999994
Network designer,10,Network designer,56821,0.999996
"Vice President, Client Service",10,"Vice President, Client Service",56822,0.999998
Senior Demand Planning Analyst,10,Senior Demand Planning Analyst,56823,1.000000

In [23]:
companies_count = companies[companies >= 10]

companies_count = pd.DataFrame(companies_count, columns=['Count'])
companies_count['Companies'] = companies_count.index
companies_count['Rank'] = range(1,len(companies_count)+1)
companies_count['Cumulative Probability'] = np.cumsum(companies_count.Count)/np.sum(companies_count.Count)

print('Number of companies', len(companies_count))
companies_count

Number of companies 87979

,Count,Companies,Rank,Cumulative Probability
IBM,21927,IBM,1,0.004894
Ernst & Young,16914,Ernst & Young,2,0.008670
Accenture,15755,Accenture,3,0.012186
Microsoft,12929,Microsoft,4,0.015072
Hewlett-Packard,11680,Hewlett-Packard,5,0.017679
Deloitte,11557,Deloitte,6,0.020259
KPMG,10411,KPMG,7,0.022582
Procter & Gamble,10222,Procter & Gamble,8,0.024864
Unilever,10155,Unilever,9,0.027131
PricewaterhouseCoopers,9190,PricewaterhouseCoopers,10,0.029182
PwC,9023,PwC,11,0.031196
Freelance,8317,Freelance,12,0.033052
HSBC,8260,HSBC,13,0.034896
Schlumberger,7953,Schlumberger,14,0.036671
Ericsson,7698,Ericsson,15,0.038390
GlaxoSmithKline,7541,GlaxoSmithKline,16,0.040073
Pfizer,7136,Pfizer,17,0.041666
Nokia,7060,Nokia,18,0.043241
Oracle,6811,Oracle,19,0.044762
Google,6712,Google,20,0.046260
Novartis,6127,Novartis,21,0.047627
Tata Consultancy Services,6110,Tata Consultancy Services,22,0.048991
Johnson & Johnson,6107,Johnson & Johnson,23,0.050354
Bank of America,5988,Bank of America,24,0.051691
Deutsche Bank,5930,Deutsche Bank,25,0.053014
Dell,5620,Dell,26,0.054269
Cisco Systems,5515,Cisco Systems,27,0.055500
BP,5310,BP,28,0.056685
Kraft Foods,5281,Kraft Foods,29,0.057864
Shell,5145,Shell,30,0.059012
...,...,...,...,...
GovNet,10,GovNet,87950,0.999935
IBM de Colombia,10,IBM de Colombia,87951,0.999938
"Centro Interdipartimentale di Ricerca ""E. Piaggio""",10,"Centro Interdipartimentale di Ricerca ""E. Piag...",87952,0.999940
Mama Group,10,Mama Group,87953,0.999942
ELEB,10,ELEB,87954,0.999944
Essen International AB,10,Essen International AB,87955,0.999946
N(3),10,N(3),87956,0.999949
Epitaph Records,10,Epitaph Records,87957,0.999951
THINK PR,10,THINK PR,87958,0.999953
Silimed,10,Silimed,87959,0.999955
Ateneo Impresa,10,Ateneo Impresa,87960,0.999958
Cranford Johnson Robinson Woods,10,Cranford Johnson Robinson Woods,87961,0.999960
Oxfordshire and Buckinghamshire Mental Health NHS Foundation Trust,10,Oxfordshire and Buckinghamshire Mental Health ...,87962,0.999962
IAP Company Ltd.,10,IAP Company Ltd.,87963,0.999964
Gallagher Financial Systems,10,Gallagher Financial Systems,87964,0.999967
Laselva Bookstore,10,Laselva Bookstore,87965,0.999969
SENTEL GSM,10,SENTEL GSM,87966,0.999971
JWT India,10,JWT India,87967,0.999973
"The Oberoi, Bangalore",10,"The Oberoi, Bangalore",87968,0.999975
Saipem Ltd,10,Saipem Ltd,87969,0.999978
UC Berkeley School of Information,10,UC Berkeley School of Information,87970,0.999980
Van der Veen & Kromhout,10,Van der Veen & Kromhout,87971,0.999982
BforBank,10,BforBank,87972,0.999984
Miele Netherlands B.V,10,Miele Netherlands B.V,87973,0.999987
TemplateMonster.com,10,TemplateMonster.com,87974,0.999989
Monberg & Thorsen A/S,10,Monberg & Thorsen A/S,87975,0.999991
KBAC,10,KBAC,87976,0.999993
Andersson Elffers Felix,10,Andersson Elffers Felix,87977,0.999996
Valtech India,10,Valtech India,87978,0.999998
Polyplex Corporation Limited,10,Polyplex Corporation Limited,87979,1.000000

In [24]:
schools_count = schools[schools >= 10]

schools_count = pd.DataFrame(schools_count, columns=['Count'])
schools_count['Schools'] = schools_count.index
schools_count['Rank'] = range(1,len(schools_count)+1)
schools_count['Cumulative Probability'] = np.cumsum(schools_count.Count)/np.sum(schools_count.Count)

print('Number of schools', len(schools_count))
schools_count

Number of schools 26071

,Count,Schools,Rank,Cumulative Probability
Fundação Getúlio Vargas,7808,Fundação Getúlio Vargas,1,0.002708
University of Mumbai,7615,University of Mumbai,2,0.005350
Universidad Complutense de Madrid,7543,Universidad Complutense de Madrid,3,0.007966
Universidad de Buenos Aires,6802,Universidad de Buenos Aires,4,0.010325
University of Toronto,6650,University of Toronto,5,0.012632
University of Phoenix,6191,University of Phoenix,6,0.014779
Delhi University,6065,Delhi University,7,0.016883
"University of California, Berkeley",6017,"University of California, Berkeley",8,0.018970
University of Michigan,5859,University of Michigan,9,0.021002
The University of Texas at Austin,5854,The University of Texas at Austin,10,0.023033
University of Cambridge,5737,University of Cambridge,11,0.025022
Stanford University,5726,Stanford University,12,0.027009
Universiteit van Amsterdam,5698,Universiteit van Amsterdam,13,0.028985
University of Illinois at Urbana-Champaign,5693,University of Illinois at Urbana-Champaign,14,0.030960
McGill University,5423,McGill University,15,0.032841
Cornell University,5396,Cornell University,16,0.034712
Universiteit Utrecht,5393,Universiteit Utrecht,17,0.036583
Penn State University,5383,Penn State University,18,0.038450
Universidade de São Paulo,5277,Universidade de São Paulo,19,0.040280
Monash University,5249,Monash University,20,0.042101
Katholieke Universiteit Leuven,5180,Katholieke Universiteit Leuven,21,0.043898
University of New South Wales,4841,University of New South Wales,22,0.045577
New York University,4694,New York University,23,0.047205
Rijksuniversiteit Groningen,4670,Rijksuniversiteit Groningen,24,0.048825
Politecnico di Milano,4669,Politecnico di Milano,25,0.050444
Universidad Politécnica de Madrid,4632,Universidad Politécnica de Madrid,26,0.052051
University of Pune,4625,University of Pune,27,0.053655
Purdue University,4603,Purdue University,28,0.055252
Michigan State University,4600,Michigan State University,29,0.056847
University of Sydney,4596,University of Sydney,30,0.058441
...,...,...,...,...
Goole Grammar School,10,Goole Grammar School,26042,0.999899
Hong Kong Productivity Council,10,Hong Kong Productivity Council,26043,0.999903
Калининградский Государственный Технический Университет (КГТУ),10,Калининградский Государственный Технический Ун...,26044,0.999906
North Berwick High School,10,North Berwick High School,26045,0.999910
Cloud County Community College,10,Cloud County Community College,26046,0.999913
Jami'at Al-Basrah,10,Jami'at Al-Basrah,26047,0.999917
Hong Kong Management Association,10,Hong Kong Management Association,26048,0.999920
Rijkshogeschool Groningen,10,Rijkshogeschool Groningen,26049,0.999924
"National Institute of Technology, Patna",10,"National Institute of Technology, Patna",26050,0.999927
HTX Hillerød,10,HTX Hillerød,26051,0.999931
Hamilton Southeastern High School,10,Hamilton Southeastern High School,26052,0.999934
Fachhochschul-Studiengänge Burgenland,10,Fachhochschul-Studiengänge Burgenland,26053,0.999938
Property Council of Australia,10,Property Council of Australia,26054,0.999941
Alma Graduate School Bologna,10,Alma Graduate School Bologna,26055,0.999945
FIT - Faculdade Impacta de Tecnologia,10,FIT - Faculdade Impacta de Tecnologia,26056,0.999948
Pokhara University,10,Pokhara University,26057,0.999951
Maneckji Cooper,10,Maneckji Cooper,26058,0.999955
Etiler Lisesi,10,Etiler Lisesi,26059,0.999958
IFPNL,10,IFPNL,26060,0.999962
UNIVERSIDAD DE A CORUÑA,10,UNIVERSIDAD DE A CORUÑA,26061,0.999965
Gokhale Memorial Girls' School,10,Gokhale Memorial Girls' School,26062,0.999969
Trinity College of Music,10,Trinity College of Music,26063,0.999972
Western Nebraska Community College,10,Western Nebraska Community College,26064,0.999976
DJ Sindh Govt. Science College,10,DJ Sindh Govt. Science College,26065,0.999979
Crabeth College Gouda,10,Crabeth College Gouda,26066,0.999983
Ordem dos Revisores Oficiais de Contas,10,Ordem dos Revisores Oficiais de Contas,26067,0.999986
ELS,10,ELS,26068,0.999990
CDAC-ACTS,10,CDAC-ACTS,26069,0.999993
"Khalsa College, Delhi University",10,"Khalsa College, Delhi University",26070,0.999997
"University of Pretoria, South Africa",10,"University of Pretoria, South Africa",26071,1.000000

In [25]:
majors_count = majors[majors >= 10]

majors_count = pd.DataFrame(majors_count, columns=['Count'])
majors_count['Majors'] = majors_count.index
majors_count['Rank'] = range(1,len(majors_count)+1)
majors_count['Cumulative Probability'] = np.cumsum(majors_count.Count)/np.sum(majors_count.Count)

print('Number of majors', len(majors_count))
majors_count

Number of majors 16376

,Count,Majors,Rank,Cumulative Probability
Computer Science,60186,Computer Science,1,0.032916
Marketing,49475,Marketing,2,0.059974
Economics,43383,Economics,3,0.083701
Finance,33985,Finance,4,0.102287
Mechanical Engineering,33410,Mechanical Engineering,5,0.120559
Business Administration,32054,Business Administration,6,0.138090
Accounting,31414,Accounting,7,0.155270
Law,27550,Law,8,0.170338
Business,21372,Business,9,0.182026
Psychology,19873,Psychology,10,0.192895
Management,19690,Management,11,0.203663
Electrical Engineering,19488,Electrical Engineering,12,0.214321
Information Technology,16263,Information Technology,13,0.223216
Civil Engineering,15724,Civil Engineering,14,0.231815
"Business Administration and Management, General",15312,"Business Administration and Management, General",15,0.240189
Chemical Engineering,14426,Chemical Engineering,16,0.248079
Chemistry,12898,Chemistry,17,0.255133
Business Management,12487,Business Management,18,0.261962
English,11848,English,19,0.268442
Commerce,11817,Commerce,20,0.274905
Engineering,11616,Engineering,21,0.281258
Science,11178,Science,22,0.287371
Mathematics,10636,Mathematics,23,0.293188
Computer Engineering,10270,Computer Engineering,24,0.298805
Architecture,10267,Architecture,25,0.304420
Physics,10222,Physics,26,0.310010
International Business,9873,International Business,27,0.315410
Project Management,9221,Project Management,28,0.320453
Political Science,8686,Political Science,29,0.325203
Industrial Engineering,8210,Industrial Engineering,30,0.329693
...,...,...,...,...
Public Management and Governance,10,Public Management and Governance,16347,0.999841
Economics and society,10,Economics and society,16348,0.999847
Economics-Accounting,10,Economics-Accounting,16349,0.999852
Financial Analysis and Investment Management,10,Financial Analysis and Investment Management,16350,0.999858
GOP,10,GOP,16351,0.999863
Business Management and Accounting,10,Business Management and Accounting,16352,0.999869
Son,10,Son,16353,0.999874
Comptabilité et gestion,10,Comptabilité et gestion,16354,0.999880
Latin - Sciences,10,Latin - Sciences,16355,0.999885
matematicas,10,matematicas,16356,0.999891
Piano performance,10,Piano performance,16357,0.999896
Commercial Recreation,10,Commercial Recreation,16358,0.999902
Biochemsitry,10,Biochemsitry,16359,0.999907
FEA,10,FEA,16360,0.999912
EDUCAÇÃO FÍSICA,10,EDUCAÇÃO FÍSICA,16361,0.999918
Translational Medicine,10,Translational Medicine,16362,0.999923
Mercados Financeiros,10,Mercados Financeiros,16363,0.999929
Journalism and Economics,10,Journalism and Economics,16364,0.999934
Energia Eólica,10,Energia Eólica,16365,0.999940
"Chemistry, Mathematics, Physics",10,"Chemistry, Mathematics, Physics",16366,0.999945
"Biology, Physics",10,"Biology, Physics",16367,0.999951
3d Animation,10,3d Animation,16368,0.999956
Sleep Medicine,10,Sleep Medicine,16369,0.999962
Commercial management,10,Commercial management,16370,0.999967
International Buisness,10,International Buisness,16371,0.999973
Certificate in Recruitment Practice,10,Certificate in Recruitment Practice,16372,0.999978
Agriculture Science,10,Agriculture Science,16373,0.999984
"Risk, Crisis and Disaster Management",10,"Risk, Crisis and Disaster Management",16374,0.999989
Strategy and General Management,10,Strategy and General Management,16375,0.999995
BOTANY,10,BOTANY,16376,1.000000